//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accommodation
    {
        public Accommodation()
        {
            this.FamilySocials = new HashSet<FamilySocial>();
        }
    
        public System.Guid AccommodationId { get; set; }
        public string AccommmodationName { get; set; }
    
        public virtual ICollection<FamilySocial> FamilySocials { get; set; }
    }
}
