//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentOrigin
    {
        public AssessmentOrigin()
        {
            this.Assessments = new HashSet<Assessment>();
        }
    
        public System.Guid AssesmentOriginId { get; set; }
        public string AssesmentOriginName { get; set; }
    
        public virtual ICollection<Assessment> Assessments { get; set; }
    }
}
