//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public System.Guid AssesmentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> duration { get; set; }
        public string time { get; set; }
        public Nullable<System.Guid> AssesmentType_fk { get; set; }
        public System.Guid Worker_fk { get; set; }
        public Nullable<System.Guid> Origin_fk { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
    
        public virtual AssessmentOrigin AssessmentOrigin { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
