//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarePlanStatus
    {
        public CarePlanStatus()
        {
            this.CarePlans = new HashSet<CarePlan>();
        }
    
        public System.Guid CarePlanStatusId { get; set; }
        public string CarePlanStatusName { get; set; }
    
        public virtual ICollection<CarePlan> CarePlans { get; set; }
    }
}
