//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarePlan
    {
        public System.Guid CarePlanID { get; set; }
        public System.Guid CarePlanType { get; set; }
        public System.Guid CarePlanStatus { get; set; }
        public string CarePlanRemarks { get; set; }
        public System.DateTime CarePlanDate { get; set; }
        public Nullable<bool> CarePlanDisable { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
    
        public virtual CarePlanStatus CarePlanStatus1 { get; set; }
        public virtual CarePlanType CarePlanType1 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
