//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseConferance
    {
        public System.Guid CaseConferanceId { get; set; }
        public Nullable<System.DateTime> CaseConferanceDate { get; set; }
        public string CaseConferancePoint { get; set; }
        public string CaseConferanceResolution { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
