//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosisPatient
    {
        public DiagnosisPatient()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public System.Guid DiagnosisId { get; set; }
        public Nullable<System.Guid> DiagnosisType_fk { get; set; }
        public int PatientId_fk { get; set; }
        public System.DateTime DiagnosisDate { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    
        public virtual DiagnosisType DiagnosisType { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
