//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosisType
    {
        public DiagnosisType()
        {
            this.DiagnosisPatients = new HashSet<DiagnosisPatient>();
        }
    
        public System.Guid DiagnosisId { get; set; }
        public string DiagnosisName { get; set; }
    
        public virtual ICollection<DiagnosisPatient> DiagnosisPatients { get; set; }
    }
}
