//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorType
    {
        public DoctorType()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public System.Guid DoctorTypeId { get; set; }
        public string DoctorTypeName { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
