//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public System.Guid DoctorID { get; set; }
        public Nullable<int> PatientId_FK { get; set; }
        public Nullable<System.Guid> DoctorType_FK { get; set; }
        public Nullable<System.DateTime> DoctorDate { get; set; }
        public Nullable<System.Guid> DEmployeeId_FK { get; set; }
        public string DoctorName { get; set; }
    
        public virtual DoctorType DoctorType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
