//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public System.Guid EquipmentId { get; set; }
        public Nullable<System.DateTime> EquipmentDate { get; set; }
        public Nullable<System.Guid> EquipmentType_fk { get; set; }
        public string EquipmentRemarks { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
