//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilySocial
    {
        public FamilySocial()
        {
            this.PatientsIncomes = new HashSet<PatientsIncome>();
        }
    
        public System.Guid FamilySocialId { get; set; }
        public Nullable<System.Guid> SocialPatientStatus_fk { get; set; }
        public Nullable<System.Guid> SocialOccupation_fk { get; set; }
        public Nullable<System.Guid> SocialAccommodations_fk { get; set; }
        public Nullable<int> SocialNoOfChildren { get; set; }
        public string SocialProblems { get; set; }
        public string FamilyHistory { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
        public Nullable<int> SocialNumberOfFloors { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PatientStatus PatientStatus { get; set; }
        public virtual ICollection<PatientsIncome> PatientsIncomes { get; set; }
    }
}
