//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionalAssessmentType
    {
        public FunctionalAssessmentType()
        {
            this.FunctionalAssesments = new HashSet<FunctionalAssesment>();
        }
    
        public System.Guid FunctionalAssessmentTypeId { get; set; }
        public string FunctionalAssessmentType1 { get; set; }
    
        public virtual ICollection<FunctionalAssesment> FunctionalAssesments { get; set; }
    }
}
