//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralObservation
    {
        public System.Guid GeneralObservationId { get; set; }
        public Nullable<System.Guid> GeneralObservationType { get; set; }
        public string GeneralObservationRemarks { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
        public Nullable<bool> GeneralObservationDisable { get; set; }
    
        public virtual GeneralObservationType GeneralObservationType1 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
