//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public Income()
        {
            this.PatientsIncomes = new HashSet<PatientsIncome>();
        }
    
        public System.Guid IncomeId { get; set; }
        public string IncomeName { get; set; }
    
        public virtual ICollection<PatientsIncome> PatientsIncomes { get; set; }
    }
}
