//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Island
    {
        public Island()
        {
            this.Localities = new HashSet<Locality>();
        }
    
        public System.Guid IslandId { get; set; }
        public string IslandName { get; set; }
    
        public virtual ICollection<Locality> Localities { get; set; }
    }
}
