//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locality
    {
        public Locality()
        {
            this.Streets = new HashSet<Street>();
        }
    
        public System.Guid LocalityId { get; set; }
        public string LocalityName { get; set; }
        public Nullable<System.Guid> Island_fk { get; set; }
    
        public virtual Island Island { get; set; }
        public virtual ICollection<Street> Streets { get; set; }
    }
}
