//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public System.Guid MedicationId { get; set; }
        public Nullable<System.DateTime> MedicationDate { get; set; }
        public string MedicationDescription { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
