//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospiceSysEntities : DbContext
    {
        public HospiceSysEntities()
            : base("name=HospiceSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Accommodation> Accommodations { get; set; }
        public virtual DbSet<AllergiesSpiritual> AllergiesSpirituals { get; set; }
        public virtual DbSet<AssessmentOrigin> AssessmentOrigins { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<AssessmentType> AssessmentTypes { get; set; }
        public virtual DbSet<CarePlan> CarePlans { get; set; }
        public virtual DbSet<CarePlanStatus> CarePlanStatuses { get; set; }
        public virtual DbSet<CarePlanType> CarePlanTypes { get; set; }
        public virtual DbSet<CaseConferance> CaseConferances { get; set; }
        public virtual DbSet<DeceasedPlace> DeceasedPlaces { get; set; }
        public virtual DbSet<DiagnosisPatient> DiagnosisPatients { get; set; }
        public virtual DbSet<DiagnosisType> DiagnosisTypes { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorType> DoctorTypes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<FamilySocial> FamilySocials { get; set; }
        public virtual DbSet<FileStatus> FileStatuses { get; set; }
        public virtual DbSet<FunctionalAssesment> FunctionalAssesments { get; set; }
        public virtual DbSet<FunctionalAssessmentType> FunctionalAssessmentTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GeneralObservation> GeneralObservations { get; set; }
        public virtual DbSet<GeneralObservationType> GeneralObservationTypes { get; set; }
        public virtual DbSet<IllnessesMedical> IllnessesMedicals { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Island> Islands { get; set; }
        public virtual DbSet<Locality> Localities { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MedicalType> MedicalTypes { get; set; }
        public virtual DbSet<Medication> Medications { get; set; }
        public virtual DbSet<NextOfKin> NextOfKins { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<OriginOfReferral> OriginOfReferrals { get; set; }
        public virtual DbSet<PatientAssesment> PatientAssesments { get; set; }
        public virtual DbSet<PatientAssessmentGrade> PatientAssessmentGrades { get; set; }
        public virtual DbSet<PatientAssessmentType> PatientAssessmentTypes { get; set; }
        public virtual DbSet<PatientAwareness> PatientAwarenesses { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientsEmployee> PatientsEmployees { get; set; }
        public virtual DbSet<PatientsIncome> PatientsIncomes { get; set; }
        public virtual DbSet<PatientStatus> PatientStatuses { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Physiotherapy> Physiotherapies { get; set; }
        public virtual DbSet<PhysiotherapyType> PhysiotherapyTypes { get; set; }
        public virtual DbSet<Problem> Problems { get; set; }
        public virtual DbSet<ProblemType> ProblemTypes { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<RelativeAwareness> RelativeAwarenesses { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<Symptomatology> Symptomatologies { get; set; }
        public virtual DbSet<SymptomatologyGrade> SymptomatologyGrades { get; set; }
        public virtual DbSet<SymptomatologyType> SymptomatologyTypes { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
    }
}
