//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextOfKin
    {
        public NextOfKin()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid NextOfKinId { get; set; }
        public Nullable<System.Guid> Personfk { get; set; }
        public Nullable<System.Guid> Relation_fk { get; set; }
        public string OtherRelationship { get; set; }
        public string NextOfKinRemark { get; set; }
        public Nullable<bool> PrimaryRelation { get; set; }
        public Nullable<bool> ContactRelation { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
        public Nullable<bool> supportNetworkRelation { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Person Person { get; set; }
        public virtual Relation Relation { get; set; }
    }
}
