//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsIncome
    {
        public System.Guid IncomeIdFk { get; set; }
        public System.Guid FamilySocialIdFk { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual FamilySocial FamilySocial { get; set; }
        public virtual Income Income { get; set; }
    }
}
