//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAssesment
    {
        public System.Guid Type { get; set; }
        public System.Guid Grade { get; set; }
        public string Remark { get; set; }
        public System.Guid PatientAssesmentId { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
    
        public virtual PatientAssessmentGrade PatientAssessmentGrade { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
