//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.AllergiesSpirituals = new HashSet<AllergiesSpiritual>();
            this.Assessments = new HashSet<Assessment>();
            this.CarePlans = new HashSet<CarePlan>();
            this.CaseConferances = new HashSet<CaseConferance>();
            this.Doctors = new HashSet<Doctor>();
            this.Equipments = new HashSet<Equipment>();
            this.FamilySocials = new HashSet<FamilySocial>();
            this.FunctionalAssesments = new HashSet<FunctionalAssesment>();
            this.GeneralObservations = new HashSet<GeneralObservation>();
            this.IllnessesMedicals = new HashSet<IllnessesMedical>();
            this.Medications = new HashSet<Medication>();
            this.PatientAssesments = new HashSet<PatientAssesment>();
            this.PatientsEmployees = new HashSet<PatientsEmployee>();
            this.Physiotherapies = new HashSet<Physiotherapy>();
            this.Problems = new HashSet<Problem>();
            this.Symptomatologies = new HashSet<Symptomatology>();
        }
    
        public int FileNumber { get; set; }
        public System.DateTime DateOfFirstContact { get; set; }
        public Nullable<System.Guid> OriginOfReferral_fk { get; set; }
        public Nullable<System.Guid> DeceasedPlace_fk { get; set; }
        public Nullable<System.DateTime> DeceasedDate { get; set; }
        public string DeceasedPlaceOther { get; set; }
        public Nullable<System.Guid> Oncologist_fk { get; set; }
        public Nullable<System.Guid> Consultant_fk { get; set; }
        public string Religion { get; set; }
        public Nullable<System.Guid> Diagnosis_fk { get; set; }
        public Nullable<System.Guid> PatientAware_fk { get; set; }
        public Nullable<System.Guid> RelativesAware_fk { get; set; }
        public Nullable<System.Guid> FamilyDoctor_fk { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> FileStatus_fk { get; set; }
        public Nullable<System.Guid> Personfk { get; set; }
    
        public virtual ICollection<AllergiesSpiritual> AllergiesSpirituals { get; set; }
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<CarePlan> CarePlans { get; set; }
        public virtual ICollection<CaseConferance> CaseConferances { get; set; }
        public virtual DeceasedPlace DeceasedPlace { get; set; }
        public virtual DiagnosisPatient DiagnosisPatient { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<FamilySocial> FamilySocials { get; set; }
        public virtual FileStatus FileStatus { get; set; }
        public virtual ICollection<FunctionalAssesment> FunctionalAssesments { get; set; }
        public virtual ICollection<GeneralObservation> GeneralObservations { get; set; }
        public virtual ICollection<IllnessesMedical> IllnessesMedicals { get; set; }
        public virtual ICollection<Medication> Medications { get; set; }
        public virtual OriginOfReferral OriginOfReferral { get; set; }
        public virtual ICollection<PatientAssesment> PatientAssesments { get; set; }
        public virtual PatientAwareness PatientAwareness { get; set; }
        public virtual Person Person { get; set; }
        public virtual RelativeAwareness RelativeAwareness { get; set; }
        public virtual ICollection<PatientsEmployee> PatientsEmployees { get; set; }
        public virtual ICollection<Physiotherapy> Physiotherapies { get; set; }
        public virtual ICollection<Problem> Problems { get; set; }
        public virtual ICollection<Symptomatology> Symptomatologies { get; set; }
    }
}
