//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAssessmentGrade
    {
        public PatientAssessmentGrade()
        {
            this.PatientAssesments = new HashSet<PatientAssesment>();
        }
    
        public System.Guid PatientAssessmentGradeId { get; set; }
        public string PatientAssessmentGradeName { get; set; }
        public Nullable<System.Guid> PatientAssessmentTypeId_fk { get; set; }
    
        public virtual ICollection<PatientAssesment> PatientAssesments { get; set; }
        public virtual PatientAssessmentType PatientAssessmentType { get; set; }
    }
}
