//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Employees = new HashSet<Employee>();
            this.NextOfKins = new HashSet<NextOfKin>();
            this.Patients = new HashSet<Patient>();
        }
    
        public System.Guid PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender_fk { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> TelephoneNo { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> Property_fk { get; set; }
        public Nullable<System.Guid> Title_fk { get; set; }
        public string IdCardNumber { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<NextOfKin> NextOfKins { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual Property Property { get; set; }
        public virtual Title Title { get; set; }
    }
}
