//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysiotherapyType
    {
        public PhysiotherapyType()
        {
            this.Physiotherapies = new HashSet<Physiotherapy>();
        }
    
        public System.Guid PhysiotherapyTypeId { get; set; }
        public string PhysiotherapyType1 { get; set; }
    
        public virtual ICollection<Physiotherapy> Physiotherapies { get; set; }
    }
}
