//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physiotherapy
    {
        public System.Guid PhysiotherapyId { get; set; }
        public Nullable<System.Guid> PhysiotherapyType { get; set; }
        public string PhysiotherapyRemarks { get; set; }
        public Nullable<System.Guid> LocationIdPhy { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
        public Nullable<bool> PhysiotherapyDisable { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PhysiotherapyType PhysiotherapyType1 { get; set; }
    }
}
