//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public System.Guid ProblemsId { get; set; }
        public Nullable<System.Guid> ProblemsType { get; set; }
        public string ProblemsDescription { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
        public Nullable<bool> ProblemsDisable { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ProblemType ProblemType { get; set; }
    }
}
