//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemType
    {
        public ProblemType()
        {
            this.Problems = new HashSet<Problem>();
        }
    
        public System.Guid ProblemTypeId { get; set; }
        public string ProblemType1 { get; set; }
    
        public virtual ICollection<Problem> Problems { get; set; }
    }
}
