//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public System.Guid PropertyId { get; set; }
        public string PropertyName { get; set; }
        public Nullable<System.Guid> Street_fk { get; set; }
    
        public virtual ICollection<Person> Persons { get; set; }
        public virtual Street Street { get; set; }
    }
}
