//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public Relation()
        {
            this.NextOfKins = new HashSet<NextOfKin>();
        }
    
        public System.Guid RelationId { get; set; }
        public string RelationName { get; set; }
    
        public virtual ICollection<NextOfKin> NextOfKins { get; set; }
    }
}
