//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public System.Guid StreetId { get; set; }
        public string StreetName { get; set; }
        public Nullable<System.Guid> Locality_fk { get; set; }
    
        public virtual Locality Locality { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
