//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptomatology
    {
        public System.Guid SymptomatologyId { get; set; }
        public Nullable<int> PatientId_fk { get; set; }
        public Nullable<System.Guid> SymptomatologyType { get; set; }
        public Nullable<System.Guid> SymptomatologyGrade { get; set; }
        public string SymptomatologyRemark { get; set; }
        public Nullable<System.Guid> LocationIdSym { get; set; }
        public Nullable<bool> SymptomatologyDisable { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual SymptomatologyGrade SymptomatologyGrade1 { get; set; }
        public virtual SymptomatologyType SymptomatologyType1 { get; set; }
    }
}
