//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymptomatologyType
    {
        public SymptomatologyType()
        {
            this.Symptomatologies = new HashSet<Symptomatology>();
        }
    
        public System.Guid SymptomatologyTypeId { get; set; }
        public string SymptomatologyType1 { get; set; }
    
        public virtual ICollection<Symptomatology> Symptomatologies { get; set; }
    }
}
